[package]
name = "hlk-uashosts"
version = "1.0.0"
edition = "2021"
description = "通过 DNSPod API 查询域名 IP 并更新本地 hosts 文件"

[dependencies]
ureq = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
winres = "0.1"

[[bin]]
name = "hlk-uashosts"
path = "src/main.rs"
